name: Deploy Website

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1
      - name: Build Passionwaves Media
        run: |
          cd articles
          python3 build.py
      - name: Deploy Passionwaves Media to S3 (/articles)
        run: |
          aws s3 sync ./articles/public s3://${{ secrets.S3_BUCKET_NAME }}/articles --delete
      - name: Deploy portfolio to S3 (root)
        run: |
          aws s3 cp ./index.html s3://${{ secrets.S3_BUCKET_NAME }}/index.html
      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"
